version: '3.8'

services:
  app:
    container_name: seed-desafio-cdc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: seed_user
      DATABASE_PASSWORD: seed_user_pass
      DATABASE_NAME: bookstore
      PORT: 8082
    command: npm run start:dev

  db:
    container_name: postgres_db_bookstore
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: seed_user
      POSTGRES_PASSWORD: seed_user_pass
      POSTGRES_DB: bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U seed_user -d bookstore" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
